insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA50187', 'CARRIER', 'Benger', 'Woodfield', '86-(785)287-9524', 'bwoodfield0@shareasale.com', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA55568', 'CARRIER', 'Turrill', 'Carney', '1-(408)763-5728', 'rcarney1@msu.edu', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35461', 'CLERK', 'Gallo', 'Siderfin', '967-(712)932-1356', 'wsiderfin2@fotki.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA35801', 'CARRIER', 'Bradwell', 'Goody', '232-(262)694-9236', 'dgoody3@arstechnica.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL50101', 'CLERK', 'Rapi', 'Suthren', '62-(694)173-1281', 'asuthren4@msn.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35897', 'CLERK', 'McShee', 'Lusk', '20-(760)938-1067', 'plusk5@paginegialle.it', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL30270', 'CLERK', 'Botterill', 'Towner', '351-(717)860-0440', 'etowner6@wordpress.org', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL67060', 'CLERK', 'Oboy', 'Wicklin', '970-(433)312-3702', 'gwicklin7@mashable.com', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35846', 'CLERK', 'Le Leu', 'Fairlaw', '359-(461)916-6596', 'afairlaw8@shinystat.com', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL54264', 'CLERK', 'McCrow', 'Rangall', '86-(204)452-3035', 'zrangall9@redcross.org', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35385', 'CLERK', 'de Keep', 'Gatley', '7-(305)198-3768', 'jgatleya@pbs.org', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL49362', 'CLERK', 'Matessian', 'Tovey', '351-(241)694-6100', 'ctoveyb@amazon.co.jp', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA50483', 'CARRIER', 'Peaden', 'Crush', '86-(388)324-6359', 'scrushc@ask.com', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL56418', 'CLERK', 'Ghelardoni', 'Quinnelly', '1-(750)623-4288', 'gquinnellyd@independent.co.uk', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL45084', 'CLERK', 'Daintith', 'Slorach', '380-(424)309-5103', 'hslorache@ed.gov', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL63046', 'CLERK', 'Kynoch', 'Whitten', '269-(665)142-8603', 'cwhittenf@washingtonpost.com', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA54167', 'CARRIER', 'Bastow', 'Belliveau', '375-(403)465-6375', 'dbelliveaug@desdev.cn', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA35344', 'CARRIER', 'Trevarthen', 'Whitmore', '1-(783)725-2600', 'gwhitmoreh@vinaora.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA35707', 'CARRIER', 'Congreve', 'Mumford', '92-(351)952-6074', 'wmumfordi@engadget.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL54715', 'CLERK', 'Sprason', 'Leguey', '84-(977)380-2234', 'blegueyj@storify.com', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35774', 'CLERK', 'Tritten', 'Elloy', '63-(474)538-0299', 'melloyk@flickr.com', 'AVAILABLE');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA37428', 'CARRIER', 'Kleinplac', 'Chirm', '62-(244)862-7072', 'lchirml@cargocollective.com', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA35762', 'CARRIER', 'Ruf', 'Seviour', '86-(951)582-4782', 'bseviourm@wordpress.org', 'SICK');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CA33794', 'CARRIER', 'Pynn', 'Stillmann', '86-(787)333-2733', 'lstillmannn@illinois.edu', 'ON-DUTY');
insert into Employees (EmployeeId, Role, Firstname, Lastname, Phone, Email, Availability) values ('CL35306', 'CLERK', 'Willey', 'Mattityahou', '86-(965)262-6002', 'jmattityahouo@google.co.jp', 'SICK');
